---
- name: Install dependencies
  ansible.builtin.apt:
    name: ca-certificates, curl
    state: present
    update_cache: true

- name: Add key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin
    state: present
